#!/bin/bash
ANIMAL="kitty"
cowsay -f bunny Welcome to our simple SHELL written by Karen Campo and David
sleep 2
cowsay -f $ANIMAL "        CASE 1 (test /bin/ls)       "
sleep 2
printf "/bin/ls\n\n"
echo "/bin/ls" | ./hsh
echo -e "[\033[32mOK\033[37m]"
sleep 1

cowsay -f $ANIMAL "        CASE 2  (test /bin/l)           "
sleep 2
printf ="/bin/l\n\n"
echo "/bin/l" | ./hsh
sleep 2
echo -e "[\033[32mOK\033[37m]"
sleep 1

cowsay -f $ANIMAL "        CASE 3  (test pwd)           "
sleep 2
printf ="pwd\n"
echo "pwd" | ./hsh
sleep 2
echo -e "[\033[32mOK\033[37m]"
sleep 1

cowsay -f $ANIMAL "        CASE 4  (test env)           "
sleep 2
printf ="env\n"
echo "env" | ./hsh
sleep 2
echo -e "[\033[32mOK\033[37m]"
sleep 1

cowsay -f $ANIMAL "        CASE 5  (test exit)           "
sleep 2
printf ="exit hola\n"
echo "exit hola" | ./hsh
sleep 2
printf ="exit\n"
echo "exit" | ./hsh
sleep 2
echo -e "Error code: "$?
echo -e "[\033[32mOK\033[37m]"

cowsay -f $ANIMAL "   FINAL  CASE  (test ls with arguments)      "
sleep 2
printf ="ls -la"
echo "ls -a" | ./hsh
sleep 2
printf ="ls -lar\n"
sleep 2
echo "ls -ar" | ./hsh
sleep 2
echo -e "[\033[32mOK\033[37m]"